version: '3.8'
services:
  asb_server:
    build:
      context: .
      target: development
    ports:
      - "9010:9010"
      - "9011:9011"
    volumes:
      - ./:/app
    depends_on:
      - asb_mysqlserver

  asb_mysqlserver:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=asb
      - MYSQL_PASSWORD=asb1111
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=asb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - asb_mysql_data:/var/lib/mysql
      - asb_mysql_config:/etc/mysql/conf.d
volumes:
  asb_mysql_data:
  asb_mysql_config: